name: photogram
description: Photogram - application for sharing photos, social network.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  cloud_firestore: ^4.3.1
  file_picker: ^5.2.5
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  overlay_support: ^2.1.0
  path: ^1.8.2
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true